version: "3.5"
services:
  server1:
    build: ./hbsrv
    hostname: hbsrv
    domainname: tim.com
    volumes:
      - type: "volume"
        source: hbdata
        target: /hbase-data
      - type: "volume"
        source: hblogs
        target: /hbase/logs
    ports:
      # External:Internal
      - "9090:9090"
    networks:
      - my-netname


  websrv:
    build: ./websrv
    hostname: photoweb
    domainname: tim.com
    ports:
      # External:Internal
      - "5001:80"
    networks:
       - my-netname

volumes:
    hbdata:
    hblogs:


networks:
  my-netname:
   name: tim
