from  proxylogger_img

#Running Alpine Linux so a litle different to add a package
#Not sure if it is my network speed
#run apk update
#add gcc produced some "coffee" error/issue. This gets a general DEV Setting sorted
#run apk add build-base
add run.sh /usr/local/bin/run.sh
run chmod +x /usr/local/bin/run.sh &&\
    pip3 install --no-index --find-links=/mnt/py3modules/ CherryPy HappyBase 
ENTRYPOINT ["/usr/local/bin/run.sh"]
CMD []
